DATA = [
    {
        "order": 2,
        "ticker": "ORGO",
        "company": "Orgaordergenesis Holdings Inc",
        "sector": "Healthcare",
        "country": "USA",
        "short_float": "18.59%",
        "float": "59.76M",
        "rel_volume": 89.14,
        "volume": 6155279,
        "price": 5.56,
        "change": "42.93%",
        "news_time": 540  # minutes (9 hours)
    },
    {
        "order": 1,
        "ticker": "BKYI",
        "company": "Bio-Key International Inc",
        "sector": "Industrials",
        "country": "USA",
        "short_float": "0.36%",
        "float": "5.64M",
        "rel_volume": 429.16,
        "volume": 168438727,
        "price": 1.04,
        "change": "63.86%",
        "news_time": 360  # minutes (6 hours)
    },
    {
        "order": 3,
        "ticker": "HLLY",
        "company": "Holley Inc",
        "sector": "Consumer Cyclical",
        "country": "USA",
        "float": "76.13M",
        "short_float": "1.58%",
        "rel_volume": 58.49,
        "volume": 3858634,
        "price": 3.40,
        "change": "24.73%",
        "news_time": 60  # minutes (1 hour)
    },
    {
        "order": 4,
        "ticker": "TNDM",
        "company": "Tandem Diabetes Care Inc",
        "sector": "Healthcare",
        "country": "USA",
        "short_float": "13.81%",
        "float": "66.89M",
        "rel_volume": 3.27,
        "volume": 615845,
        "price": 16.45,
        "change": "24.73%",
        "news_time": 180  # minutes (3 hours)
    },
    {
        "order": 5,
        "ticker": "EB",
        "company": "Eventbrite Inc",
        "sector": "Communication Services",
        "country": "USA",
        "short_float": "4.20%",
        "float": "73.89M",
        "rel_volume": 5.70,
        "volume": 299014,
        "price": 2.68,
        "change": "21.94%",
        "news_time": 540  # minutes (9 hours)
    },
    {
        "order": 6,
        "ticker": "NATR",
        "company": "Nature's Sunshine Products, Inc",
        "sector": "Consumer Defensive",
        "country": "USA",
        "short_float": "1.61%",
        "float": "13.45M",
        "rel_volume": 4.62,
        "volume": 39250,
        "price": 16.21,
        "change": "18.09%",
        "news_time": 540  # minutes (9 hours)
    },
    {
        "order": 7,
        "ticker": "FIGS",
        "company": "Figs Inc",
        "sector": "Consumer Cyclical",
        "country": "USA",
        "short_float": "6.71%",
        "float": "147.38M",
        "rel_volume": 4.28,
        "volume": 734510,
        "price": 8.88,
        "change": "18.02%",
        "news_time": 540  # minutes (9 hours)
    },
    {
        "order": 8,
        "ticker": "KODK",
        "company": "Eastman Kodak Co",
        "sector": "Industrials",
        "country": "USA",
        "short_float": "13.54%",
        "float": "51.57M",
        "rel_volume": 5.65,
        "volume": 693839,
        "price": 6.86,
        "change": "17.30%",
        "news_time": 540  # minutes (9 hours)
    },
    {
        "order": 9,
        "ticker": "NHTC",
        "company": "Natural Health Trends Corp",
        "sector": "Consumer Cyclical",
        "country": "Hong Kong",
        "short_float": "0.46%",
        "float": "7.47M",
        "rel_volume": 2.53,
        "volume": 8783,
        "price": 2.90,
        "change": "15.08%",
        "news_time": 240  # minutes (4 hours)
    },
    {
        "order": 10,
        "ticker": "TXG",
        "company": "10x Geordermics Inc",
        "sector": "Healthcare",
        "country": "USA",
        "short_float": "11.36%",
        "float": "110.42M",
        "rel_volume": 5.40,
        "volume": 1304625,
        "price": 14.61,
        "change": "12.38%",
        "news_time": 180  # minutes (3 hours)
    }
]