version: "3.9"

services:
  pyfinviz:
  # docker run -p 4000:4000 -v pyfinviz_data:/app/db_results -e NEWS_DATE_TODAY="true" --name pyfinviz2 nurhanhasan/my-pyfinviz:v1.0.0
  # docker run -it -p 4000:4000 -v pyfinviz_data:/app/db_results -e NEWS_DATE_TODAY="true" --name pyfinviz2 nurhanhasan/my-pyfinviz:v1.0.0 python3 -m cmd.cli
  # docker run -it -p 4000:4000 -v pyfinviz_data:/app/db_results -e NEWS_DATE_TODAY="true" --name pyfinviz2 nurhanhasan/my-pyfinviz:v1.0.0 sh
    container_name: pyfinviz
    build:
      context: .
      dockerfile: Dockerfile
    image: nurhanhasan/my-pyfinviz:v1.0.0
    environment:
      - NEWS_DATE_TODAY=true
    networks:
      - my_pyfinviz_network
    ports:
      - "4000:4000"
    volumes:
      - pyfinviz_data:/app/db_results

# Assign external volume for persistent data storage
# docker volume create pyfinviz_data
volumes:
  pyfinviz_data:
    external: true

networks:
  my_pyfinviz_network:
    driver: bridge